language: java

jdk:
  - oraclejdk8

install: true

script: gradle test uploadArchives closeAndReleaseRepository -Pversion="1.0.${TRAVIS_BUILD_NUMBER}"
  --refresh-dependencies --no-daemon --no-parallel

cache:
  directories:
    - "$HOME/.gradle/caches"
    - "$HOME/.gradle/wrapper"

before_install:
  - wget https://services.gradle.org/distributions/gradle-4.10.2-bin.zip
  - unzip gradle-4.10.2-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.10.2
  - export PATH=$GRADLE_HOME/bin:$PATH

  - openssl aes-256-cbc -K $encrypted_c70f72981147_key -iv $encrypted_c70f72981147_iv
    -in travis-secrets.tar.enc -out travis-secrets.tar -d

  - tar xvf travis-secrets.tar
